language: C

os:
  - linux
  - osx
sudo: required
env:
  global:
    - DEPS_DIR="${HOME}/deps"
    - COVERAGE="true"
    - secure: "co+NmbYLEZWq3AgsvgYY1P6WSzsp4/5X1o1R/oXKsaSP7UIkYoI2rwkPgugAPBAt27K/wZUEXlzYGtb9EiW27NhRnnI1H4g3Qe9RRUl6x8Zs/g+KI/s5E68Srb8wdfTXCD2ANguBUniYgMGT4ti3ZzXyVaCrIlMApbrVjBwZ+f3qf7Dv41yj+yzk8AjbjL5cYnczdjmL0dtGVFknoOu50dMN5ZigTdD6Fn+sY7Xt3HBMCSJuRAKP4s7rEOMa1qWhchFX1sAiM/+tWr4vewNpaKkQE4VefnZ2TvZZPGhfd+gZ7VR/eDDKIw3G0MEzGNO/wjsgjr86S44QyUGY4ZNuP3bmFAlFumk0j45eFWznks75EIkQGEXZudZFaDIgderhU2NYc5weQI/4eaouDeH8vZavbwiazLfoj4G6RbrKKx8gr4TNp5AehCrau6YzgLtZ3reoaftLfvYapc3Y5o5eXuPFqBuOnaFwkhV4S5tazxb7U9h9KzK5Jg0X5CBadJfzJEraayutv+GZtnbFBEZ9e25GiB9CFvF3TMRIYm4lfs1UlJXFiNpRmKgOTsmk4JcIK565JvEz44x4VxR9moBVIsycyfD2C36DCtmnUGdDhSkg/ziWIhxmfjWYU2GtloDw3Q7D9Yj484abyyaBTzKk/tw/RQn6JdfxKdwNEBAV5xs="
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.5"
    - PYTHON_VERSION="3.6"
install: bash ci/travis/install.sh
script: bash ci/travis/script.sh
branches:
  only:
  - master
  - continuous_integration


deploy:
 # Deploy to Anaconda.org
  - provider: script
    script: "bash $TRAVIS_BUILD_DIR/ci/travis/deploy.sh"
    on:
        branch: continuous_integration
    #   tags: true
    skip_cleanup: true
