# Not a .NET project. We build it in the install script
build: false

platform:
  - x64
  - x86

environment:
  ANACONDA_TOKEN:
    secure: yom1od1sZI7nYAFSmHDtgmRrLCGdkSaow11rIdIA+k8RI82Tk76rl0vOQNr3QXcX
  PYPI_USERNAME:
    secure: Exuqw/eu1vpjKcqg9TmxOQ==
  PYPI_PASSWORD:
    secure: Xr3yKtbelrxmnH0sFDzvxA==
  matrix:
    # - PYTHON_VERSION: 2.7
    #   MINICONDA: C:\Miniconda
    #   CMAKE_PROJECT: MinGW Makefiles
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda
      CMAKE_PROJECT: MinGW Makefiles


init:
  # Uncomment for remote desktop debug
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ECHO %PYTHON_VERSION% %MINICONDA%

install:
  - "%APPVEYOR_BUILD_FOLDER%\\ci\\appveyor\\install.cmd"

test_script:
  - "%APPVEYOR_BUILD_FOLDER%\\ci\\appveyor\\script.cmd"

deploy_script:
  - "%APPVEYOR_BUILD_FOLDER%\\ci\\appveyor\\deploy.cmd"


on_finish:
  # Uncomment for remote desktop debug
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
